name: Niall Bunting
description: Niall Bunting's Personal Website.
meta_description: "Niall Bunting's Personal Website. Which contains various information about him."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.niallbunting.com/blog/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://www.niallbunting.com/blog/'
author:         'Niall Bunting'
